exec-once = /home/mier/bin/clipse-start.sh # run listener on startup with proper setup

windowrule = match:class ^(clipse)$, float on # ensure you have a floating window class set if you want this behavior
windowrule = match:class ^(clipse)$, size 622 652 # set the size of the window as necessary
windowrule = match:class ^(clipse)$, center on

bind = $mainMod, X, exec, alacritty --class="clipse" -e /home/mier/bin/clipse
