exec-once = bash -c 'clipse -listen-shell &'

windowrule = match:class ^(clipse)$, float on
windowrule = match:class ^(clipse)$, size 622 652
windowrule = match:class ^(clipse)$, center on

bind = $mainMod, X, exec, alacritty --class=clipse -e clipse
