exec-once = /home/mier/bin/clipse-start.sh # run listener on startup with proper setup

windowrulev2 = float,class:(clipse) # ensure you have a floating window class set if you want this behavior
windowrulev2 = size 622 652,class:(clipse) # set the size of the window as necessary
windowrulev2 = center,class:(clipse) # center the window

bind = $mainMod, X, exec, alacritty --class="clipse" -e /home/mier/bin/clipse
