exec-once = waybar
exec-once = hyprpaper
exec-once = hyprsunset
exec-once = blueman
exec-once = nm-applet
exec-once = pnpm self-update; pnpm update -g
exec-once = /home/mier/dotfiles/.config/hypr/scripts/workspace-monitor.sh
exec-once = /home/mier/dotfiles/.config/hypr/scripts/restore-workspace-dirs.sh
exec-once = hyprctl setcursor macOS 32
exec-once = xrdb -merge ~/.Xresources
exec-once = gsettings set org.gnome.desktop.interface cursor-theme macOS && gsettings set org.gnome.desktop.interface cursor-size 32
exec-once = 1password
exec-once = sleep 3 && flatpak run com.slack.Slack
exec-once = /home/mier/dotfiles/.config/hypr/scripts/hyprbars-filter.sh
