# workspace 1 en monitor Q27q-20
workspace=1,monitor:desc:Lenovo Group Limited Q27q-20 UPP019DM

# workspace 2 en monitor N27q con firefox
workspace=2,monitor:desc:Lenovo Group Limited N27q UT331799,on-created-empty:$browser

workspace=7,monitor:desc:Lenovo Group Limited 0x40A9
workspace=8,monitor:eDP-1,on-created-empty:flatpak run com.spotify.Client
workspace=9,monitor:eDP-1,on-created-empty:flatpak run md.obsidian.Obsidian

# reglas de ventana para asegurar que las apps vayan a sus workspaces
windowrulev2 = workspace 7, class:^(Slack)$
# windowrulev2 = workspace 2, class:^(firefox)$
