git:
  overrideGpg: true
  pagers:
    - colorArg: always
      pager: "delta --dark --paging=never"
      useConfig: false
gui:
  nerdFontsVersion: "3"
  border: single
os:
  editPreset: "code"
  notARepository: skip
disableStartupPopups: false
