git:
  overrideGpg: true
  paging:
    colorArg: always
    pager: "delta --dark --paging=never"
    useConfig: false

gui:
  nerdFontsVersion: "3"

os:
  editPreset: "zed"

disableStartupPopups: false
