workspace=1,monitor:desc:LG Electronics LG ULTRAGEAR+ 206NTLE8L184
workspace=2,monitor:desc:ViewSonic Corporation VX2757 0x01010101
workspace=3,monitor:desc:HP Inc. HP 32 Display CNC04112Z7

windowrule = match:class ^(com\.slack\.Slack)$, workspace 2
windowrule = match:class ^(discord)$, workspace 2
windowrule = match:class ^(1Password)$, workspace 1
