workspace=1,monitor:desc:Lenovo Group Limited Q27q-20 UPP019DM
workspace=2,monitor:desc:Lenovo Group Limited N27q UT331799
workspace=7,monitor:desc:Lenovo Group Limited 0x40A9
workspace=8,monitor:eDP-1
workspace=9,monitor:eDP-1

windowrule = match:class ^(com\.slack\.Slack)$, workspace 7
