alias killjob="kill -SIGKILL %1"
alias spicetify="~/git/spicetify-cli/spicetify"
alias sherlock="python3 ~/git/sherlock/sherlock"
alias alacrittyrc="gedit ~/.config/alacritty/alacritty.yml"
alias nfrc="nano ~/.config/neofetch/config.conf"
alias nf=neofetch
alias cls=clear
alias nethogs="sudo nethogs"
alias "cd.."="cd .."
alias remove="sudo dnf remove -y"
alias install="sudo dnf install -y"
alias update="sudo dnf update -y"
alias upgrade="sudo dnf update -y ; flatpak update -y ; spicetify upgrade ; spicetify update"
alias grep='grep --color=auto'
alias server="ssh server@192.168.0.88"
alias pi="ssh pi@192.168.0.2"
alias htb="sudo openvpn ~/Downloads/*.ovpn"
alias nmap="sudo nmap"
alias hc="headsetcontrol"
