$browser = zen-browser
$terminal = alacritty
$fileManager = nautilus
$ide = code
$menu = rofi -show drun -show-icons
$mainMod = SUPER

source = ./land/startup.conf
source = ./land/notifications.conf
source = ./land/monitors.conf
source = ./land/clipse.conf
source = ./land/binds.conf
source = ./land/workspaces.conf

source = ./machines/current/monitors.conf
source = ./machines/current/workspaces.conf
source = ./machines/current/startup.conf

env = XCURSOR_THEME,macOS
env = XCURSOR_SIZE,32
env = HYPRCURSOR_THEME,macOS
env = HYPRCURSOR_SIZE,32
env = GTK_USE_PORTAL,1

general {
    gaps_in = 2.5
    gaps_out = 5
    border_size = 2
    col.active_border = rgba(ffffffee) rgba(fce300ee) 45deg
    col.inactive_border = rgba(595959aa)
    resize_on_border = false
    allow_tearing = true
    layout = dwindle
}

decoration {
    rounding = 0
    active_opacity = 1.0
    inactive_opacity = 0.9

    shadow {
        enabled = false
        range = 4
        render_power = 3
        color = rgba(1a1a1aee)
    }

    blur {
        enabled = false
        size = 3
        passes = 1

        vibrancy = 0.1696
    }
}

animations {
    enabled = false
}

dwindle {
    preserve_split = true
}

master {
    new_status = master
}

misc {
    force_default_wallpaper = 1
    disable_hyprland_logo = true
}

input {
    kb_layout = es
    kb_variant =
    kb_model =
    kb_options =
    kb_rules =

    follow_mouse = 1
    sensitivity = 0

    touchpad {
        natural_scroll = true
    }
}

windowrule = match:class .*, suppress_event maximize
windowrule = match:class ^$, match:title ^$, match:xwayland true, match:float true, match:fullscreen false, match:pin false, no_focus on
windowrule = match:class ^(1Password)$, float on
