# hyprlock configuration

general {
    disable_loading_bar = true
    grace = 1
    hide_cursor = true
    no_fade_in = false
    no_fade_out = false
    ignore_empty_input = false
}

background {
    monitor =
    path = screenshot
    blur_passes = 3
    blur_size = 8
    noise = 0.0117
    contrast = 0.8916
    brightness = 0.8172
    vibrancy = 0.1696
    vibrancy_darkness = 0.0
}

# hora y fecha
label {
    monitor =
    text = cmd[update:1000] echo "$TIME"
    color = rgba(200, 200, 200, 1.0)
    font_size = 55
    font_family = TX-02
    position = -100, 70
    halign = right
    valign = bottom
    shadow_passes = 5
    shadow_size = 10
}

label {
    monitor =
    text = cmd[update:60000] echo "$(date +'%A, %B %d, %Y')"
    color = rgba(200, 200, 200, 1.0)
    font_size = 20
    font_family = TX-02
    position = -100, 10
    halign = right
    valign = bottom
    shadow_passes = 5
    shadow_size = 10
}

# campo de entrada para password
input-field {
    monitor =
    size = 300, 50
    outline_thickness = 3
    dots_size = 0.33
    dots_spacing = 0.15
    dots_center = true
    dots_rounding = 0
    outer_color = rgba(115, 161, 255, 1)
    inner_color = rgba(26, 27, 38, 0.8)
    font_color = rgba(205, 214, 244, 1)
    fade_on_empty = true
    fade_timeout = 1000
    placeholder_text = <i>Enter Password...</i>
    hide_input = true
    rounding = 0
    check_color = rgba(166, 227, 161, 1)
    fail_color = rgba(243, 139, 168, 1)
    fail_text = <i>$FAIL <b>($ATTEMPTS)</b></i>
    fail_transition = 300
    capslock_color = rgba(249, 226, 175, 1)
    numlock_color = -1
    bothlock_color = -1
    invert_numlock = false
    swap_font_color = false
    
    position = 0, -20
    halign = center
    valign = center
}

# mensaje de usuario
label {
    monitor =
    text = $USER
    color = rgba(205, 214, 244, 1.0)
    font_size = 18
    font_family = TX-02
    
    position = 0, 50
    halign = center
    valign = center
    shadow_passes = 5
    shadow_size = 10
}

# mensaje de bloqueo
label {
    monitor =
    text = Locked
    color = rgba(205, 214, 244, 0.8)
    font_size = 14
    font_family = TX-02
    
    position = 0, 80
    halign = center
    valign = center
    shadow_passes = 5
    shadow_size = 10
}