{
  imports = [
    ./audio.nix
    ./boot.nix
    ./desktop.nix
    ./docker.nix
    ./envfs.nix
    ./flatpak.nix
    ./fonts.nix
    ./i18n.nix
    ./network.nix
    ./nix-ld.nix
    ./nix-settings.nix
    ./security.nix
    ./services.nix
    ./users.nix
    ./vpn.nix
  ];
}
