
# ~/.config/starship.toml
# ----- PROMPT -----
add_newline = false
right_format = '''$rust$ruby$python$docker_context$package$php$c$nodejs$java $cmd_duration$custom$memory_usage$time$battery$status$aws'''
command_timeout = 100000
format = '''$os$all'''

# ----- GENERAL -----

[os]
format = "[$symbol]($style)"
disabled = true

[os.symbols]
Macos = " "
Windows = " "
Fedora = " "
Ubuntu = " "
Arch = " "
Debian = " "
CentOS = " "
Pop = " "
Raspbian = " "
RedHatEnterprise = " "

[time]
time_format = "%T"
format = " $time($style) "
style = "bright-white"
disabled = false

[line_break]
disabled = true

[character]
success_symbol = "[%](bold green)"
error_symbol = "[%](bold red)"

[cmd_duration]
min_time = 5000
format = "took [$duration]($style) "
show_milliseconds = true
disabled = true

[directory]
truncation_length = 2
format = "[$path](green)[$lock_symbol]($lock_style) "

[git_branch]
format = "[$symbol](bold bg:202)[ $branch](202) "
symbol = ""
truncation_length = 9
truncation_symbol = "·"

[git_commit]
commit_hash_length = 8
style = "bold white"

[username]
style_user = "bold white"
style_root = "bold yellow"
show_always = true
format = "[$user]($style)[@](blue)"

[hostname]
ssh_only = false
format = "[$hostname]($style) "
trim_at = "-"
style = "bold yellow"
disabled = false

[memory_usage]
format = "[$symbol$ram_pct!]($style) "
threshold = 70
style = "bold dimmed red"
disabled = false
symbol = " "

[status]
disabled = false
symbol = ''

[git_status]
untracked = ''
deleted = ''
renamed = ''
modified = ''
staged = '[+$count](green)'
stashed = '\$'
ahead = '⇡${count}'
diverged = '⇕⇡${ahead_count}⇣${behind_count}'
behind = '⇣${count}'
format = '([$all_status$ahead_behind]($style) )'

# ----- PACKAGES -----

[package]
format = "[$symbol]($style)[$version](white) "
disabled = false

[python]
format = "[$symbol](blue)[$version](bold yellow) "
symbol = " "
version_format = "${major}.${minor}"

[rust]
format = "[$symbol]($style)"

[ruby]
symbol = " "
version_format = "${major}.${minor}"
format = "[$symbol($version)]($style) "

[php]
symbol = " "
format = "[$symbol$version]($style) "
version_format = "${major}.${minor}"

[c]
format = '[$symbol]($style)'
symbol = ' '

[nodejs]
format = "[$symbol$version]($style)"
version_format = "${major}"
disabled = false

[java]
format = "[$symbol](bold red dimmed)[$version ]($style)"
symbol = " "
version_format = "${major}"
detect_files = [
	"pom.xml",
	"build.gradle.kts",
	"build.sbt",
	".java-version",
	"deps.edn",
	"project.clj",
	"build.boot",
	"build.xml",
	"manifest.mf",
]

[docker_context]
symbol = "󰡨 "
format = '[$symbol]($style)'

[aws]
symbol = " "
format = '[$symbol]($style)'
region_aliases = { "eu-west-3" = "EUW3" }
disabled = true

[terraform]
format = '[$symbol]($style)'
symbol = '󱁢 '

[golang]
format = '[$symbol]($style)'
symbol = ' '

# ----- BATTERY -----

[battery]
full_symbol = "󱊣 "
charging_symbol = "󱊥 "
discharging_symbol = "󱊢 "
empty_symbol = "󱃍 "
disabled = true

[[battery.display]]
threshold = 10
style = "bold red"

[[battery.display]]
threshold = 25
style = "bold orange"

[[battery.display]]
threshold = 50
style = "bold yellow"

[[battery.display]]
threshold = 90
style = "bold green"

[[battery.display]]
threshold = 100
style = "bold purple"
