
[window]
resize_increments = true

[window.dimensions]
columns = 125
lines = 30

[cursor.style]
blinking = "On"
shape = "Beam"

[env]
TERM = "xterm-256color"

[font]
size = 11.5

[font.normal]
family = "BerkeleyMono Nerd Font"

[keyboard]
bindings = [
    { key = "V", mods = "Control", action = "Paste" },
    { key = "Backspace", mods = "Control", chars = "\u0017" },
]


[[mouse.bindings]]
action = "Paste"
mouse = "Right"

[general]
import = ["~/.config/alacritty/blood-moon.toml"]
